# Generated by Django 2.1.5 on 2022-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='accountName',
            field=models.CharField(max_length=128),
        ),
    ]
