# Generated by Django 2.1.5 on 2022-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blance',
            field=models.IntegerField(default=0),
        ),
    ]
