# Generated by Django 2.1.5 on 2022-03-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_userprofile_blance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='blance',
            new_name='balance',
        ),
    ]
