# Generated by Django 2.1.5 on 2022-03-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20220320_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameaccount',
            name='category',
            field=models.CharField(max_length=128),
        ),
    ]
