# Generated by Django 2.1.5 on 2022-03-07 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_category_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='category',
            name='views',
        ),
    ]
