# Generated by Django 2.1.5 on 2022-03-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20220321_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
