# Generated by Django 2.1.5 on 2022-03-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
