# Generated by Django 2.1.5 on 2022-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=128, unique=True)),
                ('passwork', models.CharField(max_length=128)),
                ('discription', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
