# Generated by Django 2.1.5 on 2022-03-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0010_gameaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='category',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='discription',
            field=models.CharField(max_length=128),
        ),
    ]
