# Generated by Django 2.1.5 on 2022-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_auto_20220311_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameaccount',
            old_name='passwork',
            new_name='password',
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
