# Generated by Django 2.1.5 on 2022-03-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20220311_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameaccount',
            old_name='likes',
            new_name='price',
        ),
    ]
