# Generated by Django 2.1.5 on 2022-03-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20220311_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameaccount',
            old_name='discription',
            new_name='description',
        ),
    ]
