# Generated by Django 2.1.5 on 2022-03-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20220311_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameaccount',
            name='seller',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='status',
            field=models.CharField(default='onSale', max_length=128),
        ),
    ]
