# Generated by Django 2.1.5 on 2022-03-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_auto_20220311_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
