# Generated by Django 2.1.5 on 2022-03-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0015_auto_20220319_1634'),
        ('rango', '0015_remove_userprofile_website'),
    ]

    operations = [
    ]
