# Generated by Django 2.1.5 on 2022-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20220320_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.CharField(max_length=128),
        ),
    ]
